name: educalty_chat
description: "chat application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
# Flutter version is 3.22.0
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0
  # UI
  chat_bubbles: ^1.6.0
  sizer: ^2.0.15
  fluttertoast: ^8.2.8
  shimmer: ^3.0.0
  lottie: ^3.1.2
  # Core
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Italic.ttf
          style: italic
